from __future__ import annotations

from dataclasses import dataclass
import json
import pickle
from pathlib import Path
import random
import tarfile

import numpy as np
import torch
import torch.nn.functional as F
import torch.utils.data as data
import torchvision.transforms as T
from torch.autograd import Variable
from torchvision import datasets
from PIL import Image, ImageFilter

from fedprime.utils.env import add_vendor_paths
from fedprime.data.corruptions import ID_TO_GROUP


CIFAR10_MEAN = [125.3 / 255.0, 123.0 / 255.0, 113.9 / 255.0]
CIFAR10_STD = [63.0 / 255.0, 62.1 / 255.0, 66.7 / 255.0]
CIFAR100_MEAN = [0.5070751592371323, 0.48654887331495095, 0.4409178433670343]
CIFAR100_STD = [0.2673342858792401, 0.2564384629170883, 0.27615047132568404]


@dataclass(frozen=True)
class DatasetStats:
    mean: list[float]
    std: list[float]


class GaussianBlur:
    def __init__(self, sigma=(0.1, 2.0)):
        self.sigma = sigma

    def __call__(self, x):
        sigma = random.uniform(self.sigma[0], self.sigma[1])
        return x.filter(ImageFilter.GaussianBlur(radius=sigma))


class TwoViewTransform:
    def __init__(self, transform, weak_transform):
        self.transform = transform
        self.weak_transform = weak_transform

    def __call__(self, x):
        return self.transform(x), self.weak_transform(x)


class CorruptionSkewClientDataset(data.Dataset):
    """Client-local CIFAR-10 dataset generated by the corruption-skew protocol."""

    def __init__(
        self,
        root: str | Path,
        client_id: int | None = None,
        train: bool = True,
        transform=None,
        return_corruption: bool = False,
        evaluation_split: str = "test_balanced",
    ):
        self.root = Path(root)
        self.client_id = client_id
        self.train = train
        self.transform = transform
        self.return_corruption = return_corruption
        self.evaluation_split = str(evaluation_split)
        metadata_path = self.root / "metadata.json"
        self.metadata = (
            json.loads(metadata_path.read_text(encoding="utf-8"))
            if metadata_path.is_file()
            else {}
        )
        self.corruption_names = self._load_corruption_names()
        self.corruption_splits = {
            str(name): str(split)
            for name, split in self.metadata.get("operator_splits", {}).items()
        }
        if train:
            if client_id is None:
                raise ValueError("client_id is required for corruption-skew training data.")
            data_dir = self.root / f"client_{client_id}"
            self.data = np.load(data_dir / "train_images.npy")
            self.targets = np.load(data_dir / "train_labels.npy")
            self.corruption_ids = np.load(data_dir / "train_corruption_ids.npy")
        else:
            data_dir = self.root / self.evaluation_split
            self.data = np.load(data_dir / "test_images.npy")
            self.targets = np.load(data_dir / "test_labels.npy")
            self.corruption_ids = np.load(data_dir / "test_corruption_ids.npy")

    def _load_corruption_names(self) -> dict[int, str]:
        raw = self.metadata.get("operator_to_id")
        if isinstance(raw, dict):
            return {int(value): str(name) for name, value in raw.items()}
        raw = self.metadata.get("group_to_id")
        if isinstance(raw, dict):
            return {int(value): str(name) for name, value in raw.items()}
        return {int(idx): str(name) for idx, name in ID_TO_GROUP.items()}

    def __len__(self) -> int:
        return int(self.targets.shape[0])

    def __getitem__(self, index: int):
        image = self.data[index]
        label = int(self.targets[index])
        corruption_id = int(self.corruption_ids[index])
        if self.transform is not None:
            image = self.transform(image)
        if self.return_corruption:
            return image, label, corruption_id
        return image, label


class NumpyImageClassificationDataset(data.Dataset):
    """Small fallback dataset for CIFAR tarballs when extracted files are unavailable."""

    def __init__(self, images: np.ndarray, labels: np.ndarray, transform=None):
        self.images = np.asarray(images, dtype=np.uint8)
        self.labels = np.asarray(labels, dtype=np.int64)
        self.transform = transform

    def __len__(self) -> int:
        return int(self.labels.shape[0])

    def __getitem__(self, index: int):
        image = Image.fromarray(self.images[index])
        if self.transform is not None:
            image = self.transform(image)
        return image, int(self.labels[index])


class PublicAugMixDataset(data.Dataset):
    """Pickle-safe public clean/AugMix view wrapper used by AugHFL."""

    def __init__(self, dataset) -> None:
        self.dataset = dataset
        self.preprocess = T.ToTensor()

    def __len__(self) -> int:
        return len(self.dataset)

    def __getitem__(self, index: int):
        add_vendor_paths()
        from Dataset.dataaug import aug

        image, label = self.dataset[index]
        return (
            self.preprocess(image),
            aug(image, self.preprocess),
            aug(image, self.preprocess),
        ), label


def dataset_stats(name: str) -> DatasetStats:
    if name.lower() == "cifar10":
        return DatasetStats(CIFAR10_MEAN, CIFAR10_STD)
    if name.lower() == "cifar100":
        return DatasetStats(CIFAR100_MEAN, CIFAR100_STD)
    raise ValueError(f"Unsupported dataset stats: {name}")


def normalize_batch(images: torch.Tensor, stats: DatasetStats) -> torch.Tensor:
    mean = torch.tensor(stats.mean, device=images.device).view(1, -1, 1, 1)
    std = torch.tensor(stats.std, device=images.device).view(1, -1, 1, 1)
    return (images - mean) / std


def _private_train_transform(raw_for_prime: bool):
    if raw_for_prime:
        return T.Compose([
            T.ToTensor(),
            T.Lambda(lambda x: F.pad(
                Variable(x.unsqueeze(0), requires_grad=False),
                (4, 4, 4, 4),
                mode="reflect",
            ).data.squeeze()),
            T.ToPILImage(),
            T.ColorJitter(),
            T.RandomCrop(32),
            T.RandomHorizontalFlip(),
            T.ToTensor(),
        ])
    return T.Compose([
        T.ToTensor(),
        T.Lambda(lambda x: F.pad(
            Variable(x.unsqueeze(0), requires_grad=False),
            (4, 4, 4, 4),
            mode="reflect",
        ).data.squeeze()),
        T.ToPILImage(),
        T.ColorJitter(),
        T.RandomCrop(32),
        T.RandomHorizontalFlip(),
        T.ToTensor(),
        T.Normalize(CIFAR10_MEAN, CIFAR10_STD),
    ])


def _prime_dcl_train_transform():
    base = T.Compose([
        T.ToTensor(),
        T.Lambda(lambda x: F.pad(
            Variable(x.unsqueeze(0), requires_grad=False),
            (4, 4, 4, 4),
            mode="reflect",
        ).data.squeeze()),
        T.ToPILImage(),
        T.ColorJitter(),
        T.RandomCrop(32),
        T.RandomHorizontalFlip(),
        T.ToTensor(),
    ])
    weak = T.Compose([
        T.ToTensor(),
        T.Lambda(lambda x: F.pad(
            Variable(x.unsqueeze(0), requires_grad=False),
            (4, 4, 4, 4),
            mode="reflect",
        ).data.squeeze()),
        T.ToPILImage(),
        T.RandomResizedCrop(size=32, scale=(0.2, 1.0)),
        T.RandomApply([T.ColorJitter(0.4, 0.4, 0.4, 0.1)], p=0.8),
        T.RandomGrayscale(p=0.2),
        T.RandomApply([GaussianBlur()], p=0.5),
        T.RandomHorizontalFlip(),
        T.ToTensor(),
    ])
    return TwoViewTransform(base, weak)


def _rahfl_augmix_view_transforms(dataset_name: str = "cifar10"):
    stats = dataset_stats(dataset_name)
    base = T.Compose([
        T.ToTensor(),
        T.Lambda(lambda x: F.pad(
            Variable(x.unsqueeze(0), requires_grad=False),
            (4, 4, 4, 4),
            mode="reflect",
        ).data.squeeze()),
        T.ToPILImage(),
        T.ColorJitter(),
        T.RandomCrop(32),
        T.RandomHorizontalFlip(),
    ])
    weak = T.Compose([
        T.ToTensor(),
        T.Lambda(lambda x: F.pad(
            Variable(x.unsqueeze(0), requires_grad=False),
            (4, 4, 4, 4),
            mode="reflect",
        ).data.squeeze()),
        T.ToPILImage(),
        T.RandomResizedCrop(size=32, scale=(0.2, 1.0)),
        T.RandomApply([T.ColorJitter(0.4, 0.4, 0.4, 0.1)], p=0.8),
        T.RandomGrayscale(p=0.2),
        T.RandomApply([GaussianBlur()], p=0.5),
        T.RandomHorizontalFlip(),
    ])
    preprocess = T.Compose([
        T.ToTensor(),
        T.Normalize(stats.mean, stats.std),
    ])
    return base, weak, preprocess


def _private_test_transform(dataset_name: str = "cifar10"):
    stats = dataset_stats(dataset_name)
    return T.Compose([
        T.ToTensor(),
        T.Normalize(stats.mean, stats.std),
    ])


def _prepared_private_dataset_name(root: str | Path) -> str:
    metadata_path = Path(root) / "metadata.json"
    if not metadata_path.is_file():
        return "cifar10"
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    explicit = metadata.get("private_dataset")
    if explicit:
        return str(explicit).lower()
    return "cifar100" if "cifar100" in str(metadata.get("dataset", "")).lower() else "cifar10"


def load_private_labels(cifar10c_root: str | Path, corrupt_rate: float | int) -> np.ndarray:
    add_vendor_paths()
    from Dataset.init_dataset import CIFAR_C

    ds = CIFAR_C(str(cifar10c_root), train=True, transform=None, corrupt_rate=corrupt_rate)
    return np.asarray(ds.target)


def load_corruption_skew_client_labels(root: str | Path, num_clients: int) -> dict[int, np.ndarray]:
    root = Path(root)
    labels = {}
    for client_id in range(num_clients):
        labels[client_id] = np.load(root / f"client_{client_id}" / "train_labels.npy")
    return labels


def partition_private_data(
    labels: np.ndarray,
    num_clients: int,
    num_classes: int,
    partition: str,
    dirichlet_alpha: float,
    max_samples_per_client: int | None = None,
    partition_indices_path: str | Path | None = None,
    partition_seed: int | None = None,
) -> dict[int, list[int]]:
    metadata = {
        "num_labels": int(len(labels)),
        "num_clients": int(num_clients),
        "num_classes": int(num_classes),
        "partition": str(partition),
        "dirichlet_alpha": float(dirichlet_alpha),
        "max_samples_per_client": (
            None if max_samples_per_client is None else int(max_samples_per_client)
        ),
    }
    if partition_indices_path:
        path = Path(partition_indices_path)
        if path.exists():
            return _load_partition_indices(path, metadata)

    rng = np.random.default_rng(partition_seed)
    if partition == "iid":
        mapping = _iid_partition_indices(len(labels), num_clients, rng)
    elif partition == "dirichlet":
        min_require_size = 10
        if max_samples_per_client is not None:
            min_require_size = int(max_samples_per_client)
        mapping = _dirichlet_partition_indices(
            labels=labels,
            num_classes=num_classes,
            num_clients=num_clients,
            alpha=dirichlet_alpha,
            rng=rng,
            min_require_size=min_require_size,
        )
    else:
        raise ValueError(f"Unknown partition: {partition}")

    if max_samples_per_client is not None:
        mapping = {
            client_id: list(indices[:max_samples_per_client])
            for client_id, indices in mapping.items()
        }
    if partition_indices_path:
        _save_partition_indices(Path(partition_indices_path), mapping, metadata)
    return mapping


def _iid_partition_indices(
    num_labels: int,
    num_clients: int,
    rng: np.random.Generator,
) -> dict[int, list[int]]:
    indices = rng.permutation(num_labels)
    splits = np.array_split(indices, num_clients)
    return {client_id: split.astype(np.int64).tolist() for client_id, split in enumerate(splits)}


def _dirichlet_partition_indices(
    labels: np.ndarray,
    num_classes: int,
    num_clients: int,
    alpha: float,
    rng: np.random.Generator,
    min_require_size: int = 10,
) -> dict[int, list[int]]:
    labels = np.asarray(labels)
    num_labels = labels.shape[0]
    min_size = 0
    idx_batch: list[list[int]] = [[] for _ in range(num_clients)]

    while min_size < min_require_size:
        idx_batch = [[] for _ in range(num_clients)]
        for class_id in range(num_classes):
            class_indices = np.where(labels == class_id)[0]
            rng.shuffle(class_indices)
            proportions = rng.dirichlet(np.repeat(float(alpha), num_clients))
            proportions = np.array(
                [
                    proportion * (len(client_indices) < num_labels / num_clients)
                    for proportion, client_indices in zip(proportions, idx_batch)
                ],
                dtype=np.float64,
            )
            proportions = proportions / proportions.sum()
            split_points = (np.cumsum(proportions) * len(class_indices)).astype(int)[:-1]
            for client_indices, split in zip(idx_batch, np.split(class_indices, split_points)):
                client_indices.extend(split.astype(np.int64).tolist())
        min_size = min(len(client_indices) for client_indices in idx_batch)

    mapping = {}
    for client_id, client_indices in enumerate(idx_batch):
        shuffled = np.asarray(client_indices, dtype=np.int64)
        rng.shuffle(shuffled)
        mapping[client_id] = shuffled.tolist()
    return mapping


def _load_partition_indices(path: Path, expected: dict[str, object]) -> dict[int, list[int]]:
    with np.load(path, allow_pickle=False) as data:
        if "__meta__" not in data:
            raise ValueError(f"Partition file {path} has no metadata.")
        metadata = json.loads(str(data["__meta__"].item()))
        for key, value in expected.items():
            if metadata.get(key) != value:
                raise ValueError(
                    f"Partition file {path} metadata mismatch for {key}: "
                    f"expected {value!r}, got {metadata.get(key)!r}."
                )
        mapping = {}
        for client_id in range(int(expected["num_clients"])):
            key = f"client_{client_id}"
            if key not in data:
                raise ValueError(f"Partition file {path} is missing {key}.")
            mapping[client_id] = data[key].astype(np.int64).tolist()
    return mapping


def _save_partition_indices(path: Path, mapping: dict[int, list[int]], metadata: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    arrays = {
        f"client_{client_id}": np.asarray(indices, dtype=np.int64)
        for client_id, indices in sorted(mapping.items())
    }
    np.savez_compressed(
        path,
        __meta__=json.dumps(metadata, ensure_ascii=False),
        **arrays,
    )


def build_private_loaders(
    cifar10c_root: str | Path,
    dataidx_map: dict[int, list[int]],
    train_batch_size: int,
    test_batch_size: int,
    corrupt_rate: float | int,
    test_corrupt_rate: float | int,
    num_workers: int,
    raw_for_prime: bool = True,
):
    add_vendor_paths()
    from Dataset.init_dataset import CIFAR_C

    train_loaders = []
    for client_id in sorted(dataidx_map):
        train_ds = CIFAR_C(
            str(cifar10c_root),
            dataidxs=dataidx_map[client_id],
            train=True,
            transform=_private_train_transform(raw_for_prime),
            corrupt_rate=corrupt_rate,
        )
        train_loaders.append(data.DataLoader(
            train_ds,
            batch_size=train_batch_size,
            shuffle=True,
            drop_last=True,
            num_workers=num_workers,
            pin_memory=torch.cuda.is_available(),
        ))

    test_ds = CIFAR_C(
        str(cifar10c_root),
        train=False,
        transform=_private_test_transform(),
        corrupt_rate=test_corrupt_rate,
    )
    test_loader = data.DataLoader(
        test_ds,
        batch_size=test_batch_size,
        shuffle=False,
        drop_last=False,
        num_workers=num_workers,
        pin_memory=torch.cuda.is_available(),
    )
    return train_loaders, test_loader


def build_prime_dcl_private_loaders(
    cifar10c_root: str | Path,
    dataidx_map: dict[int, list[int]],
    train_batch_size: int,
    test_batch_size: int,
    corrupt_rate: float | int,
    test_corrupt_rate: float | int,
    num_workers: int,
):
    add_vendor_paths()
    from Dataset.init_dataset import CIFAR_C

    train_loaders = []
    for client_id in sorted(dataidx_map):
        train_ds = CIFAR_C(
            str(cifar10c_root),
            dataidxs=dataidx_map[client_id],
            train=True,
            transform=_prime_dcl_train_transform(),
            corrupt_rate=corrupt_rate,
        )
        train_loaders.append(data.DataLoader(
            train_ds,
            batch_size=train_batch_size,
            shuffle=True,
            drop_last=True,
            num_workers=num_workers,
            pin_memory=torch.cuda.is_available(),
        ))

    test_ds = CIFAR_C(
        str(cifar10c_root),
        train=False,
        transform=_private_test_transform(),
        corrupt_rate=test_corrupt_rate,
    )
    test_loader = data.DataLoader(
        test_ds,
        batch_size=test_batch_size,
        shuffle=False,
        drop_last=False,
        num_workers=num_workers,
        pin_memory=torch.cuda.is_available(),
    )
    return train_loaders, test_loader


def build_augmix_private_loaders(
    cifar10c_root: str | Path,
    dataidx_map: dict[int, list[int]],
    train_batch_size: int,
    test_batch_size: int,
    corrupt_rate: float | int,
    test_corrupt_rate: float | int,
    num_workers: int,
    augmix_module: str = "jsd",
):
    add_vendor_paths()
    from Dataset.utils import get_dataloader

    train_loaders = []
    train_datasets = []
    for client_id in sorted(dataidx_map):
        train_dl, _, train_ds, _ = get_dataloader(
            dataset="cifar10",
            datadir=str(cifar10c_root),
            train_bs=train_batch_size,
            test_bs=test_batch_size,
            dataidxs=dataidx_map[client_id],
            corrupt_rate=corrupt_rate,
            test_corrupt_rate=test_corrupt_rate,
            augmix_module=augmix_module,
        )
        train_dl = data.DataLoader(
            train_ds,
            batch_size=train_batch_size,
            shuffle=True,
            drop_last=True,
            num_workers=num_workers,
            pin_memory=torch.cuda.is_available(),
        )
        train_loaders.append(train_dl)
        train_datasets.append(train_ds)

    _, test_loader, _, test_ds = get_dataloader(
        dataset="cifar10",
        datadir=str(cifar10c_root),
        train_bs=train_batch_size,
        test_bs=test_batch_size,
        corrupt_rate=corrupt_rate,
        test_corrupt_rate=test_corrupt_rate,
        augmix_module=None,
    )
    test_loader = data.DataLoader(
        test_ds,
        batch_size=test_batch_size,
        shuffle=False,
        drop_last=False,
        num_workers=num_workers,
        pin_memory=torch.cuda.is_available(),
    )
    return train_loaders, test_loader, train_datasets, test_ds


def build_corruption_skew_augmix_loaders(
    root: str | Path,
    num_clients: int,
    train_batch_size: int,
    test_batch_size: int,
    num_workers: int,
    augmix_module: str = "jsd",
):
    add_vendor_paths()
    from Dataset.dataaug import AugMixDataset

    dataset_name = _prepared_private_dataset_name(root)
    base, weak, preprocess = _rahfl_augmix_view_transforms(dataset_name)
    train_loaders = []
    train_datasets = []
    for client_id in range(num_clients):
        base_ds = CorruptionSkewClientDataset(
            root=root,
            client_id=client_id,
            train=True,
            transform=TwoViewTransform(base, weak),
            return_corruption=False,
        )
        train_ds = AugMixDataset(base_ds, preprocess, jsd_or_nojsd=augmix_module)
        train_loaders.append(data.DataLoader(
            train_ds,
            batch_size=train_batch_size,
            shuffle=True,
            drop_last=True,
            num_workers=num_workers,
            pin_memory=torch.cuda.is_available(),
        ))
        train_datasets.append(train_ds)

    test_ds = CorruptionSkewClientDataset(
        root=root,
        train=False,
        transform=_private_test_transform(dataset_name),
        return_corruption=True,
    )
    test_loader = data.DataLoader(
        test_ds,
        batch_size=test_batch_size,
        shuffle=False,
        drop_last=False,
        num_workers=num_workers,
        pin_memory=torch.cuda.is_available(),
    )
    return train_loaders, test_loader, train_datasets, test_ds


def build_fedclear_private_loaders(
    root: str | Path,
    num_clients: int,
    train_batch_size: int,
    test_batch_size: int,
    num_workers: int,
):
    """Build raw-tensor CLE-HFL loaders for online counterfactual interventions."""

    train_loaders = []
    train_datasets = []
    for client_id in range(num_clients):
        train_ds = CorruptionSkewClientDataset(
            root=root,
            client_id=client_id,
            train=True,
            transform=_private_train_transform(raw_for_prime=True),
            return_corruption=False,
        )
        train_loaders.append(data.DataLoader(
            train_ds,
            batch_size=train_batch_size,
            shuffle=True,
            drop_last=True,
            num_workers=num_workers,
            pin_memory=torch.cuda.is_available(),
        ))
        train_datasets.append(train_ds)

    test_ds = CorruptionSkewClientDataset(
        root=root,
        train=False,
        transform=_private_test_transform(),
        return_corruption=True,
    )
    test_loader = data.DataLoader(
        test_ds,
        batch_size=test_batch_size,
        shuffle=False,
        drop_last=False,
        num_workers=num_workers,
        pin_memory=torch.cuda.is_available(),
    )
    return train_loaders, test_loader, train_datasets, test_ds


def build_corruption_skew_pretrain_loaders(
    root: str | Path,
    num_clients: int,
    train_batch_size: int,
    num_workers: int,
) -> list[data.DataLoader]:
    root = Path(root)
    train_loaders = []
    for client_id in range(num_clients):
        train_ds = CorruptionSkewClientDataset(
            root=root,
            client_id=client_id,
            train=True,
            transform=_private_train_transform(raw_for_prime=False),
            return_corruption=False,
        )
        train_loaders.append(data.DataLoader(
            train_ds,
            batch_size=train_batch_size,
            shuffle=True,
            drop_last=True,
            num_workers=num_workers,
            pin_memory=torch.cuda.is_available(),
        ))
    return train_loaders


def corruption_group_names_from_test_loader(test_loader) -> list[str]:
    dataset = getattr(test_loader, "dataset", None)
    if isinstance(dataset, CorruptionSkewClientDataset):
        ids = sorted(int(idx) for idx in np.unique(dataset.corruption_ids))
        return [dataset.corruption_names.get(idx, f"group_{idx}") for idx in ids]
    return []


def _cifar100_train_from_tar(cifar100_root: str | Path) -> tuple[np.ndarray, np.ndarray]:
    root = Path(cifar100_root)
    candidates = [
        root / "cifar-100-python.tar.gz",
        root.parent / "cifar-100-python.tar.gz",
    ]
    tar_path = next((candidate for candidate in candidates if candidate.exists()), None)
    if tar_path is None:
        raise FileNotFoundError(f"Could not locate cifar-100-python.tar.gz under {root}")

    with tarfile.open(tar_path, "r:gz") as tar:
        member = tar.getmember("cifar-100-python/train")
        file_obj = tar.extractfile(member)
        if file_obj is None:
            raise FileNotFoundError(member.name)
        batch = pickle.load(file_obj, encoding="latin1")

    data_arr = batch.get("data", batch.get(b"data"))
    labels = batch.get("fine_labels", batch.get(b"fine_labels"))
    if data_arr is None or labels is None:
        raise KeyError("CIFAR-100 train batch is missing data or fine_labels.")
    images = np.asarray(data_arr, dtype=np.uint8).reshape(-1, 3, 32, 32).transpose(0, 2, 3, 1)
    targets = np.asarray(labels, dtype=np.int64)
    return images, targets


def _cifar10_train_from_tar(cifar10_root: str | Path) -> tuple[np.ndarray, np.ndarray]:
    root = Path(cifar10_root)
    candidates = [root / "cifar-10-python.tar.gz", root.parent / "cifar-10-python.tar.gz"]
    tar_path = next((candidate for candidate in candidates if candidate.exists()), None)
    if tar_path is None:
        raise FileNotFoundError(f"Could not locate cifar-10-python.tar.gz under {root}")
    image_parts, label_parts = [], []
    with tarfile.open(tar_path, "r:gz") as tar:
        for batch_id in range(1, 6):
            member = tar.getmember(f"cifar-10-batches-py/data_batch_{batch_id}")
            file_obj = tar.extractfile(member)
            if file_obj is None:
                raise FileNotFoundError(member.name)
            batch = pickle.load(file_obj, encoding="latin1")
            image_parts.append(np.asarray(batch.get("data", batch.get(b"data")), dtype=np.uint8))
            label_parts.append(np.asarray(batch.get("labels", batch.get(b"labels")), dtype=np.int64))
    images = np.concatenate(image_parts).reshape(-1, 3, 32, 32).transpose(0, 2, 3, 1)
    return images, np.concatenate(label_parts)


def build_public_loader(
    cifar100_root: str | Path,
    public_size: int,
    batch_size: int,
    num_workers: int,
    seed: int,
    download: bool,
    public_dataset: str = "cifar100",
    public_views: str = "tensor",
):
    public_views = str(public_views).lower()
    transform = None if public_views == "augmix" else T.Compose([T.ToTensor()])
    public_dataset = str(public_dataset).lower()
    if public_dataset == "cifar10_npy":
        root = Path(cifar100_root)
        image_path = root / "public_images.npy"
        if not image_path.is_file():
            raise FileNotFoundError(f"Missing in-domain public images: {image_path}")
        images = np.load(image_path)
        targets = np.zeros(len(images), dtype=np.int64)
        ds = NumpyImageClassificationDataset(images, targets, transform=transform)
    elif public_dataset == "cifar100":
        try:
            ds = datasets.CIFAR100(str(cifar100_root), train=True, transform=transform, download=download)
        except Exception as exc:
            print(f"torchvision CIFAR-100 loader failed: {exc}")
            print("Falling back to direct cifar-100-python.tar.gz reader.")
            images, targets = _cifar100_train_from_tar(cifar100_root)
            ds = NumpyImageClassificationDataset(images, targets, transform=transform)
    elif public_dataset == "cifar10":
        try:
            ds = datasets.CIFAR10(str(cifar100_root), train=True, transform=transform, download=download)
        except Exception as exc:
            print(f"torchvision CIFAR-10 loader failed: {exc}")
            print("Falling back to direct cifar-10-python.tar.gz reader.")
            images, targets = _cifar10_train_from_tar(cifar100_root)
            ds = NumpyImageClassificationDataset(images, targets, transform=transform)
    else:
        raise ValueError(f"Unsupported public dataset: {public_dataset}")
    if public_views == "augmix":
        ds = PublicAugMixDataset(ds)
    elif public_views != "tensor":
        raise ValueError(f"Unsupported public view mode: {public_views}")

    rng = np.random.default_rng(seed)
    indices = rng.choice(np.arange(len(ds)), size=min(public_size, len(ds)), replace=False)
    subset = data.Subset(ds, indices.tolist())
    loader = data.DataLoader(
        subset,
        batch_size=batch_size,
        shuffle=True,
        drop_last=True,
        num_workers=num_workers,
        pin_memory=torch.cuda.is_available(),
    )
    return loader
